#!/bin/bash
DIR=$1
BASE=$(basename $DIR)

OUT=$2

echo "Generating cache for ${DIR} to ${OUT}"
for exec in $(find $DIR -executable -type f); do ldd $exec >> /tmp/$BASE.txt; done
cat /tmp/$BASE.txt | grep -v "/usr/lib/${BASE}" | awk '{print $3}' | sort -u >> $OUT
rm /tmp/$BASE.txt
