#!/bin/bash
DIR=$1
BASE=$(basename $DIR)

echo > /tmp/$BASE.txt
for exec in $(find $DIR -executable -type f); do ldd $exec >> /tmp/$BASE.txt 2> /dev/null; done
cat /tmp/$BASE.txt | grep -v "/usr/lib/${BASE}" | awk '{print $3}' | sort -u
rm /tmp/$BASE.txt
