#!/bin/bash

find $XDG_DATA_HOME/sb/cache/ -type f -delete
for profile in $(ls $HOME/.local/bin/*.sb); do
  echo "Refreshing: ${profile}"
  $profile --dry --update-libraries --update-cache --seccomp-group
done
wait
rm -r /tmp/sb/*
rm -r /run/sb/*
