.TH "arg::config" 3 "SB++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg::config
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <arguments\&.hpp>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const std::string & \fBl_name\fP"
.br
.ti -1c
.RI "const std::string & \fBs_name\fP"
.br
.ti -1c
.RI "const std::string & \fBdef\fP = 'false'"
.br
.ti -1c
.RI "const std::string & \fBmod\fP = ''"
.br
.ti -1c
.RI "const shared::vector \fBvalid\fP = {}"
.br
.ti -1c
.RI "const bool & \fBmust_set\fP = false"
.br
.ti -1c
.RI "const custom_policy & \fBcustom\fP = custom_policy::FALSE"
.br
.ti -1c
.RI "const bool & \fBlist\fP = false"
.br
.ti -1c
.RI "const uint_fast8_t & \fBposition\fP = \-1"
.br
.ti -1c
.RI "const std::string & \fBhelp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Arguments passed to Argument\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SB++ from the source code\&.
