#!/bin/sh

export PATH="$(pwd):$PATH"

echo "Profiling application using installed SB profiles..."
for script in $(ls ~/.local/bin/*.sb); do
  
  echo "Running: $script"
  sb-clean
  $script --dry
  $script --dry
done
