#!/bin/sh

export PATH="$(pwd):$PATH"

echo "Profiling application using installed SB profiles..."
for script in $(ls ~/.local/bin/*.sb); do

  echo "Running: $script"
  $script --dry --refresh
  $script --dry
done
