#!/bin/bash

ARGS="$@"

if [[ -z $ARGS ]]; then
  ARGS="--update all"
fi

find $XDG_DATA_HOME/sb/cache/ -type f -delete

for profile in $(ls $HOME/.local/bin/*.sb); do
  echo "Refreshing: ${profile}"
  $profile --dry "$@"
done
